activation: elu
batch_size: 32
hidden_depth: 4
hidden_dim: 128
input_dim: 5
loss_bound_P_weight: 1
loss_bound_U_weight: 1
loss_bound_dUdy_weight: 1
loss_bound_k_weight: 1
loss_bound_stress_weight: 1
loss_phys_k_weight: 10
loss_phys_momentum_weight: 10
lr: 0.0001
max_steps: 3600000
output_dim: 8
rho: 1.225
